print(type("abc"))
print(type(123))
print(type(123.456))
print(type(True))

print(int("123") + int("456"))
print(float("123.456"))
print(bool("-1"))
print(bool(False))
name = input("Enter your name\n")
print("Number of letters in your name: " + str(len(name)))