print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10 12 15 "))
people = int(input("How many people to split the bill? "))
final_bill = round(bill + bill * (tip/100), 2)
print(f"Final bill is {final_bill}")
print(f"The final bill for each person is ${round(final_bill/5, 2)}")
